### PR TITLE
Add cache control headers

### PR DESCRIPTION
**Pull request by duhruh**
# Description 

This adds a new config value which allows us to adjust the TTL on the cache control http header. The default being 5*time.minute

### CODE REVIEW

**Comment by mdale** [comment]
Why 5 min ? Are the URLs not specific to the version of the asset ?

**Comment by duhruh** [comment]
@mdale i just chose an arbitrary default, i wasn't sure what to set it to, this ttl of course can be overridden by a config value. What should I set the timeout to? Would it be safe to never timeout these assets?

**Comment by mdale** [comment]
If the assets have the version in the url .. 12 months+ is ideal. If not ... unfortunately have to set it to something like 5 min and make sure you have 304 not modified request -> response supported.

**Comment by duhruh** [comment]
@mdale i've added in the 304 handling can you take another pass at this.

**Pull request merged**
